name: test-cross-platform

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'

  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'

jobs:
  build-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Set up checkout
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Set up node_modules
        run: npm ci

      - name: Build packages
        run: |
          mkdir packs
          npm pack --workspaces --pack-destination packs

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: packs
          path: ./packs

  github-actions-runner-images:
    strategy:
      matrix:
        runner-image:
          - macos-15
          - macos-14
          - macos-13
          - ubuntu-24.04
          - ubuntu-22.04
          - windows-2022
        node-version:
          - 22
          - 20
          - 18
          - 16

    runs-on: ${{ matrix.runner-image }}

    needs: build-packages

    steps:
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: .

      - name: Initialize npm
        run: npm init -y

      - name: Debug directory structure
        if: runner.os != 'Windows'
        run: ls -alR

      - name: Debug GLIBC version
        if: runner.os == 'Linux'
        run: ldd --version

      - name: Install packages
        if: runner.os != 'Windows'
        run: npm install $(find . -name "*.tgz")

      - name: Install packages
        if: runner.os == 'Windows'
        run: Get-ChildItem -Recurse -Filter *.tgz | ForEach-Object { npm install "file:$($_.FullName)" }

      - name: Test clang-format-git
        run: npx clang-format-git --help

      - name: Test clang-format-git-python
        run: npx clang-format-git-python --help

      - name: Test clang-format-node
        run: |
          npx clang-format-node --help
          npx clang-format-node --version

  docker-images:
    strategy:
      matrix:
        docker:
          - platform: arm/v7
            ubuntu-image: arm32v7
            node-name: arm
          - platform: arm64/v8
            ubuntu-image: arm64v8
            node-name: arm64
          - platform: ppc64le
            ubuntu-image: ppc64le
            node-name: ppc64
          - platform: s390x
            ubuntu-image: s390x
            node-name: s390x
        node-version:
          - 22
          - 20
          - 18
          - 16

    runs-on: ubuntu-22.04

    needs: build-packages

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: .

      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Docker run background
        run: docker run -d --name ${{ matrix.docker.node-name }} --platform linux/${{ matrix.docker.platform }} ${{ matrix.docker.ubuntu-image }}/ubuntu:22.04 tail -f /dev/null

      - name: Copy file to Docker container
        run: docker cp ./packs ${{ matrix.docker.node-name }}:/

      - name: Docker exec
        run: |
          docker exec ${{ matrix.docker.node-name }} /bin/bash -c "
            echo ---Debug uname -m--- &&
            uname -m &&

            echo ---Debug pwd--- &&
            pwd &&

            echo ---Set up dependencies--- &&
            apt update -y &&
            apt install -y curl &&
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash &&
            source ~/.nvm/nvm.sh &&

            echo ---Set up node--- &&
            nvm install ${{ matrix.node-version }} &&
            nvm use ${{ matrix.node-version}} &&

            echo ---Initialize npm--- &&
            npm init -y &&

            echo ---Debug ls -alR--- &&
            ls -alR &&

            echo ---Install packages--- &&
            find . -name "*.tgz" -exec chmod 755 {} \; &&
            npm install $(find . -name "*.tgz") &&

            echo ---Test clang-format-git--- &&
            npx clang-format-git --help &&

            echo ---Test clang-format-git-python--- &&
            npx clang-format-git-python --help &&

            ehco ---Test clang-format-node--- &&
            npx clang-format-node --help &&
            npx clang-format-node --version
          "
