name: test-cross-platform

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  run-clang-format:
    strategy:
      matrix:
        os-version:
          # - macos-14-large # macos-latest-large or macos-14-large
          - macos-14 # macos-latest, macos-14, macos-latest-xlarge or macos-14-xlarge
          # - macos-13-xlarge # macos-13-xlarge
          - macos-13 # macos-13 or macos-13-large
          - macos-12 # macos-12 or macos-12-large
          - ubuntu-24.04 # ubuntu-24.04
          - ubuntu-22.04 # ubuntu-latest or ubuntu-22.04
          # - ubuntu-20.04 # ubuntu-20.04
          - windows-2022 # windows-latest or windows-2022
          # - windows-2019 # windows-2019

    runs-on: ${{ matrix.os-version }}

    steps:
      - name: Set up checkout
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Set up node_modules
        run: npm ci

      - name: Debug GLIBC version
        if: runner.os == 'Linux'
        run: ldd --version

      - name: Build
        run: npm run build

      - name: Chmod
        run: npm run postinstall

      - name: Debug Permission
        if: runner.os != 'Windows'
        run: ls -alR build/bin

      - name: Test
        run: npx clang-format --version
