name: test-cross-platform

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  run-clang-format:
    strategy:
      matrix:
        os-version:
          - macos-14
          - macos-13
          - macos-12
          - ubuntu-24.04
          - ubuntu-22.04
          - windows-2022

    runs-on: ${{ matrix.os-version }}

    steps:
      - name: Set up checkout
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Set up node_modules
        run: npm ci

      - name: Debug GLIBC version
        if: runner.os == 'Linux'
        run: ldd --version

      - name: Build
        run: npm run build

      - name: Chmod
        run: npm run postinstall

      - name: Debug Permission
        if: runner.os != 'Windows'
        run: ls -alR build/bin

      - name: Test
        run: npx clang-format --version
