name: test-cross-platform

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'

  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'

jobs:
  github-actions-runner-images:
    strategy:
      matrix:
        runner-image:
          - macos-15
          - macos-14
          - macos-13
          - ubuntu-24.04
          - ubuntu-22.04
          - windows-2022
        node-version:
          - 22
          - 20
          - 18
          - 16

    runs-on: ${{ matrix.runner-image }}

    steps:
      - name: Set up checkout
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up node_modules
        run: npm ci

      - name: Debug GLIBC version
        if: runner.os == 'Linux'
        run: ldd --version

      - name: Build
        run: npm run build

      - name: Debug Permission
        if: runner.os != 'Windows'
        run: ls -alR packages/clang-format-node/build/bin

      - name: Test
        run: npx clang-format --version

  docker-images:
    strategy:
      matrix:
        docker:
          - platform: arm/v7
            ubuntu-image: arm32v7
            node-name: arm
          - platform: arm64/v8
            ubuntu-image: arm64v8
            node-name: arm64
          - platform: ppc64le
            ubuntu-image: ppc64le
            node-name: ppc64
          - platform: s390x
            ubuntu-image: s390x
            node-name: s390x

    runs-on: ubuntu-22.04

    steps:
      - name: Set up checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Docker run background
        run: docker run -d --name ${{ matrix.docker.node-name }} --platform linux/${{ matrix.docker.platform }} ${{ matrix.docker.ubuntu-image }}/ubuntu:22.04 tail -f /dev/null

      - name: Copy file to Docker container
        run: docker cp ./packages/clang-format-node/src/bin/cfn-linux-${{ matrix.docker.node-name }}/clang-format ${{ matrix.docker.node-name }}:/

      - name: Docker exec
        run: |
          docker exec ${{ matrix.docker.node-name }} /bin/bash -c "
            echo ---Debug uname -m--- &&
            uname -m &&

            echo ---Debug pwd--- &&
            pwd &&

            echo ---Debug ls -l /clang-format--- &&
            ls -l /clang-format &&

            echo ---Chmod--- &&
            chmod 755 /clang-format &&
            ls -l /clang-format &&

            echo ---Test--- &&
            /clang-format --version
          "
